[pytest]
pythonpath = src
markers =
    IT_preprocessing_pipeline: Integration tests for preprocessing pipeline
    PT_large_dataset: Performance tests for large datasets
    RT_zscore_outlier: Regression tests for zscore outlier detection
    ST_csv_ingestion: System tests for CSV ingestion
    UAT_medical_records: User Acceptance Tests for medical records
    UT_missing_value_handler: Unit tests for missing value handler
    VT_schema_validation: Validation tests for schema validation
